name: LeetCode Sync (backdated with placeholders)

on:
  workflow_dispatch: {}   # run manually from the Actions tab

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with full history, allow push)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 👇 Important: committer = YOU (not the bot)
      - name: Configure git user to your identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.MY_GH_EMAIL }}"

      - name: Run LeetCode backdated sync
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          AUTHOR_NAME: ${{ github.actor }}
          AUTHOR_EMAIL: ${{ secrets.MY_GH_EMAIL }}   # must be your verified GitHub email
          FORCE_RECOMMIT: "1"                        # first run: backfill everything
          PLACEHOLDER_ON_MISSING: "1"                # enable placeholders for missing code
          PLACEHOLDER_EXT: "md"                      # placeholder file extension
          REPO_PATH: ${{ github.workspace }}
          BRANCH: main
        run: |
          python leetcode_sync.py

      - name: Show last 25 commits (debug)
        run: |
          git --no-pager log -n 25 --pretty=format:"%h | %an <%ae> | %ad | %s"
