name: Update README (LeetCode)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '15 0 * * *' # daily 00:15 UTC (~05:45 IST)

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Update README
        env:
          LC_USERNAME: rana_782
          TZ_REGION: Asia/Kolkata
        run: |
          python scripts/update_readme.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(readme): auto-update LeetCode stats"
            git push
          fi
